disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Craig Yanitski"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = ""

  [params.author]
  name = "Dr. Craig Nicholas Yanitski"
  email = "yanitski@ph1.uni-koeln.de"
  image = "yanitski_logo.png"
  imageQuality = 96
  headline = "I'm only human after all"
  bio = "I am a freelance astrophysicist.."

    [[params.author.links]]
    email = "mailto:yanitski@ph1.uni-koeln.de"

    [[params.author.links]]
    github = "https://github.com/CraigYanitski"

    [[params.author.links]]
    linkedin = "https://linkedin.com/in/craig-yanitski"

    [[params.author.links]]
    orcid = "https://orcid.org/0009-0009-3294-6320"
